### ISSUE TITLE
devops-plugin add is giving list of all plugins 

### ISSUE THREAD

**Issue by sundar-godspeed** [godspeedsystems/gs-documentation#72]
![Screenshot from 2023-12-07 12-12-10](https://github.com/godspeedsystems/gs-documentation/assets/144660714/c00bdac9-a6a3-49b4-afef-f1bf5c311a23)

Godspeed help is showing devops-plugin and godspeed devops-plugin add is giving list of all plugins.
Please check if this documentation is correct
https://docs.godspeed.systems/docs/CLI#devops-plugin

**Comment by mastersilv3r** [comment]
Right now this page is down. @avtar-mindgrep can you please share by when can we get this plugin documented. Closing this issue for now.
